In [1]:
import numpy as np
import pandas as pd

In [2]:
columns = ['A','B','C','D']
index = ['Q1','Q2','Q3','Q4','Q5']

In [3]:
np.random.seed(101)
data = np.random.randint(-100,100,(5,4))
data

array([[ -5, -89, -19, -30],
       [-37, -13, -25,  37],
       [-60,  32, -37,  68],
       [-40,  92,  10, -95],
       [ 40, -60, -51, -17]])

In [4]:
df = pd.DataFrame(data=data,index=index,columns=columns)
df

     A   B   C   D
Q1  -5 -89 -19 -30
Q2 -37 -13 -25  37
Q3 -60  32 -37  68
Q4 -40  92  10 -95
Q5  40 -60 -51 -17

In [5]:
df['A']

Q1    -5
Q2   -37
Q3   -60
Q4   -40
Q5    40
Name: A, dtype: int64

In [6]:
df[['A','D']]

     A   D
Q1  -5 -30
Q2 -37  37
Q3 -60  68
Q4 -40 -95
Q5  40 -17

In [7]:
type(df['B'])

pandas.core.series.Series

In [8]:
df['NEW'] = df['B'] + df['C']
df

     A   B   C   D  NEW
Q1  -5 -89 -19 -30 -108
Q2 -37 -13 -25  37  -38
Q3 -60  32 -37  68   -5
Q4 -40  92  10 -95  102
Q5  40 -60 -51 -17 -111

In [9]:
df = df.drop('NEW',axis=1)
df

     A   B   C   D
Q1  -5 -89 -19 -30
Q2 -37 -13 -25  37
Q3 -60  32 -37  68
Q4 -40  92  10 -95
Q5  40 -60 -51 -17

In [10]:
df.loc['Q1']

A    -5
B   -89
C   -19
D   -30
Name: Q1, dtype: int64

In [11]:
df.loc[['Q1','Q4']]

     A   B   C   D
Q1  -5 -89 -19 -30
Q4 -40  92  10 -95

In [12]:
df.iloc[2]

A   -60
B    32
C   -37
D    68
Name: Q3, dtype: int64

In [13]:
df.iloc[0:2]

     A   B   C   D
Q1  -5 -89 -19 -30
Q2 -37 -13 -25  37

In [14]:
df = df.drop('Q3',axis=0)
df

     A   B   C   D
Q1  -5 -89 -19 -30
Q2 -37 -13 -25  37
Q4 -40  92  10 -95
Q5  40 -60 -51 -17

In [15]:
df.loc[['Q2','Q5'],['C','D']]

     C   D
Q2 -25  37
Q5 -51 -17

In [16]:
df > 0

        A      B      C      D
Q1  False  False  False  False
Q2  False  False  False   True
Q4  False   True   True  False
Q5   True  False  False  False

In [17]:
df[df>0]

       A     B     C     D
Q1   NaN   NaN   NaN   NaN
Q2   NaN   NaN   NaN  37.0
Q4   NaN  92.0  10.0   NaN
Q5  40.0   NaN   NaN   NaN

In [18]:
df['C']>0

Q1    False
Q2    False
Q4     True
Q5    False
Name: C, dtype: bool

In [19]:
df[df['C']>0]

     A   B   C   D
Q4 -40  92  10 -95

In [20]:
df[df['C']>0]['D']

Q4   -95
Name: D, dtype: int64

In [21]:
df[df['B']>0][['C','D']]

     C   D
Q4  10 -95

In [22]:
df[(df['A']>0) & (df['D'] < 0)]

     A   B   C   D
Q5  40 -60 -51 -17

In [23]:
df

     A   B   C   D
Q1  -5 -89 -19 -30
Q2 -37 -13 -25  37
Q4 -40  92  10 -95
Q5  40 -60 -51 -17

In [24]:
df.reset_index()

  index   A   B   C   D
0    Q1  -5 -89 -19 -30
1    Q2 -37 -13 -25  37
2    Q4 -40  92  10 -95
3    Q5  40 -60 -51 -17

In [25]:
newindex = 'HGO AGS BCS TAB'.split()
newindex

['HGO', 'AGS', 'BCS', 'TAB']

In [26]:
df['ESTADOS'] = newindex

In [27]:
df.set_index('ESTADOS')
df

     A   B   C   D ESTADOS
Q1  -5 -89 -19 -30     HGO
Q2 -37 -13 -25  37     AGS
Q4 -40  92  10 -95     BCS
Q5  40 -60 -51 -17     TAB

In [28]:
df.describe().transpose()

   count   mean        std   min    25%   50%    75%   max
A    4.0 -10.50  37.206630 -40.0 -37.75 -21.0   6.25  40.0
B    4.0 -17.50  79.433410 -89.0 -67.25 -36.5  13.25  92.0
C    4.0 -21.25  25.038304 -51.0 -31.50 -22.0 -11.75  10.0
D    4.0 -26.25  54.242511 -95.0 -46.25 -23.5  -3.50  37.0

In [29]:
df.dtypes

A           int64
B           int64
C           int64
D           int64
ESTADOS    object
dtype: object

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, Q1 to Q5
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   A        4 non-null      int64
 1   B        4 non-null      int64
 2   C        4 non-null      int64
 3   D        4 non-null      int64
 4   ESTADOS  4 non-null      object
dtypes: int64(4), object(1)
memory usage: 364.0+ bytes