In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({'k1':['A','A','B','B','C','C'],
                   'col1':[100,200,300,300,400,500],
                   'col2':['HGO','CDMX','TLX','TLX','QROO','MICH']})

In [3]:
df

  k1  col1  col2
0  A   100   HGO
1  A   200  CDMX
2  B   300   TLX
3  B   300   TLX
4  C   400  QROO
5  C   500  MICH

In [4]:
df['col2'].unique()

array(['HGO', 'CDMX', 'TLX', 'QROO', 'MICH'], dtype=object)

In [5]:
df['col2'].nunique()

5

In [6]:
df['col2'].value_counts()

col2
TLX     2
HGO     1
CDMX    1
QROO    1
MICH    1
Name: count, dtype: int64

In [7]:
df.drop_duplicates()

  k1  col1  col2
0  A   100   HGO
1  A   200  CDMX
2  B   300   TLX
4  C   400  QROO
5  C   500  MICH

In [8]:
df['NEW'] = df['col1'] * 10
df

  k1  col1  col2   NEW
0  A   100   HGO  1000
1  A   200  CDMX  2000
2  B   300   TLX  3000
3  B   300   TLX  3000
4  C   400  QROO  4000
5  C   500  MICH  5000

In [9]:
def grab_first_letter(state):
    return state[0]

In [10]:
df['FIRST'] = df['col2'].apply(grab_first_letter)

In [11]:
df

  k1  col1  col2   NEW FIRST
0  A   100   HGO  1000     H
1  A   200  CDMX  2000     C
2  B   300   TLX  3000     T
3  B   300   TLX  3000     T
4  C   400  QROO  4000     Q
5  C   500  MICH  5000     M

In [12]:
def full_name(state):
    if state[0] == 'C':
        return 'Ciudad de Mexico'
    return 'Error'

In [13]:
df['FULL NAME'] = df['col2'].apply(full_name)
df

  k1  col1  col2   NEW FIRST         FULL NAME
0  A   100   HGO  1000     H             Error
1  A   200  CDMX  2000     C  Ciudad de Mexico
2  B   300   TLX  3000     T             Error
3  B   300   TLX  3000     T             Error
4  C   400  QROO  4000     Q             Error
5  C   500  MICH  5000     M             Error

In [14]:
df['k1']

0    A
1    A
2    B
3    B
4    C
5    C
Name: k1, dtype: object

In [15]:
df['k1'].map({'A':1,'B':2,'C':3})

0    1
1    1
2    2
3    2
4    3
5    3
Name: k1, dtype: int64

In [16]:
df

  k1  col1  col2   NEW FIRST         FULL NAME
0  A   100   HGO  1000     H             Error
1  A   200  CDMX  2000     C  Ciudad de Mexico
2  B   300   TLX  3000     T             Error
3  B   300   TLX  3000     T             Error
4  C   400  QROO  4000     Q             Error
5  C   500  MICH  5000     M             Error

In [17]:
df['col1'].max()

500

In [18]:
df['col1'].idxmax()

5

In [19]:
df['col1'].min()

100

In [20]:
df['col1'].idxmin()

0

In [21]:
df.columns

Index(['k1', 'col1', 'col2', 'NEW', 'FIRST', 'FULL NAME'], dtype='object')

In [22]:
df.columns = ['C1','C2','C3','C4','C5','C6']
df

  C1   C2    C3    C4 C5                C6
0  A  100   HGO  1000  H             Error
1  A  200  CDMX  2000  C  Ciudad de Mexico
2  B  300   TLX  3000  T             Error
3  B  300   TLX  3000  T             Error
4  C  400  QROO  4000  Q             Error
5  C  500  MICH  5000  M             Error

In [23]:
df.sort_values('C3')

  C1   C2    C3    C4 C5                C6
1  A  200  CDMX  2000  C  Ciudad de Mexico
0  A  100   HGO  1000  H             Error
5  C  500  MICH  5000  M             Error
4  C  400  QROO  4000  Q             Error
2  B  300   TLX  3000  T             Error
3  B  300   TLX  3000  T             Error

In [24]:
features = pd.DataFrame({'A':[100,200,300,400,500],
                         'B':[12,13,14,15,16]})

predictions = pd.DataFrame({'pred':[0,1,1,0,1]})

In [25]:
features

     A   B
0  100  12
1  200  13
2  300  14
3  400  15
4  500  16

In [26]:
predictions

   pred
0     0
1     1
2     1
3     0
4     1

In [27]:
pd.concat([features,predictions])

       A     B  pred
0  100.0  12.0   NaN
1  200.0  13.0   NaN
2  300.0  14.0   NaN
3  400.0  15.0   NaN
4  500.0  16.0   NaN
0    NaN   NaN   0.0
1    NaN   NaN   1.0
2    NaN   NaN   1.0
3    NaN   NaN   0.0
4    NaN   NaN   1.0

In [28]:
pd.concat([features,predictions],axis=1)

     A   B  pred
0  100  12     0
1  200  13     1
2  300  14     1
3  400  15     0
4  500  16     1

In [29]:
pd.get_dummies(df['C1'])

       A      B      C
0   True  False  False
1   True  False  False
2  False   True  False
3  False   True  False
4  False  False   True
5  False  False   True